### PR TITLE
Fix failing build on solaris

### PR DESCRIPTION
**Pull request by usebaz**
Rename variable for fix conflic on sunOS.
[x] test passed

Issue: #45 
@bnoordhuis can you release also v0.2.4 with this changes?

### CODE REVIEW

**Comment by santigimeno** [comment]
@usebaz why `v0.2.4`?  Doesn't `v2.0.0` work four you?

**Comment by usebaz** [comment]
@santigimeno winston-syslog(https://github.com/winstonjs/winston-syslog) use old version: `"unix-dgram": "~0.2.1"`
and version `v0.2.4` satisfies the condition in package.json

**Comment by santigimeno** [comment]
@usebaz got it. Coincidentally, I'm also a maintainer of `winston-syslog`. I'll try to upgrade dependencies there.

**Comment by santigimeno** [comment]
Landed in https://github.com/bnoordhuis/node-unix-dgram/commit/b271dc8def38565053079e471a3a5b6ee43aa459. Thanks

**Comment by santigimeno** [comment]
Published in `v2.0.1`

**Pull request closed without merging**
