### PR TITLE
src: upgrade to nan2

### PR DESCRIPTION
**Pull request by santigimeno**
- Also replace Handle with Local.

### CODE REVIEW

**Comment by bnoordhuis** [comment]
LGTM with two suggestions:

1. I'd pin nan at `~2.0.8`.
2. You can drop the `using v8::Handle` directive.

**Comment by santigimeno** [comment]
@bnoordhuis updated per your comments. Thanks!

**Comment by bnoordhuis** [comment]
LGTM

**Comment by santigimeno** [comment]
Thanks! Merged in https://github.com/bnoordhuis/node-unix-dgram/commit/982cf6954811101dd7de9df0c3fbce4c05016ed9

**Comment by santigimeno** [comment]
Published as v0.2.2

**Pull request closed without merging**
