### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by DABH**
I am maintaining `winston-syslog` and was unable to build it due to some compiler warnings from `node-gyp` building `unix-dgram`.  It looks like everything is resolved just by bumping the dependencies of `unix-dgram`.  Any chance you could quickly merge this and do an npm release @bnoordhuis ?  Thanks so much in advance!

### CODE REVIEW

**Comment by bnoordhuis** [comment]
Checking in a lock file isn't appropriate for a library, that's for applications. Other than that no objections except that publishing to npm is such a pain in the rear nowadays that I haven't done it in a long time.

@santigimeno Did I ever give you publish rights? If not, I should have.

**Comment by santigimeno** [comment]
>  Did I ever give you publish rights? If not, I should have.

Probably you did, can't really remember tbh. Also, it's been quit a bit of time since I last published to npm. I may give it a go in a few days as I have some other modules that need to be updated.

**Comment by DABH** [comment]
@bnoordhuis Done!  Thanks so much for the quick reply :)  And thanks @santigimeno for being willing to help with a release!

I don't usually advertise other people's work, but `np` has been an awesome tool (in my opinion) for publishing to npm.  You just `npm i -g np` and run `np` in your repo dir (it takes care of the version bumping etc.).  Feels a lot easier to me than the manual way of npm publishing.  Anyway, let me know if there's anything I can do to help with getting this merged and the release out, thanks again :)

**Comment by DABH** [comment]
Any updates on possibly being able to merge and do a quick publish?  Let me know if there’s anything I can do to help — thanks again!

**Comment by DABH** [comment]
@bnoordhuis @santigimeno just another gentle follow up on this :) Thank you in advance for finding a quick moment to spare, let me know if I can help!

**Comment by santigimeno** [comment]
@DABH Landed in 389941254576cd1002dd06528682fbd004ce43b8 and published as `v2.0.6`. Yes it should have been `v2.0.5` but I messed it up and had to republish. Sorry about that.

**Comment by DABH** [comment]
You rock, thank you so much!!

**Pull request closed without merging**
